name: ProtectionZones
version: '${project.version}'
main: me.youhavetrouble.protectionzones.ProtectionZones
api-version: 1.19
authors: [ YouHaveTrouble ]
website: https://youhavetrouble.me
commands:
  protectionzones:
    description: ProtectionZones command
    aliases:
      - pz